import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const alpino = localFont({
  src: "./fonts/Alpino-Variable.woff2", 
  variable: "--font-alpino",
  weight: "100 900",
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alpino.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
